[package]
name = "reth-optimism-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "OP primitive types"

[lints]
workspace = true

[dependencies]
# reth
reth-eth-wire-types.workspace = true

# op-reth
reth-optimism-primitives.workspace = true

# ethereum
alloy-consensus.workspace = true

# optimism
op-alloy-consensus.workspace = true

[features]
default = ["std"]
std = [
	"alloy-consensus/std",
	"op-alloy-consensus/std",
	"reth-optimism-primitives/std"
]
